spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: publication-service
          uri: lb://publication-service
          predicates:
            - Path=/api/v1/books/**, /api/v1/magazines/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**


logging:
  level:
    org.springframework.cloud.gateway: DEBUG

server:
  port: 8080
