spring:
  datasource:
    url: jdbc:postgresql://localhost:8050/publications
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init_library"
    baseline-version: 0
    locations: classpath:db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8081