spring:
  application:
    name: Library
  messages:
    basename: messages
  datasource:
    url: jdbc:postgresql://library-db:5432/Library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql

management:
  endpoints:
    web:
      base-path: /int/v1/
      exposure:
        include: "health"
  endpoint:
    health:
      access: read_only
      show-details: always
  health:
    defaults:
      enabled: false
    db:
      enabled: true

springdoc:
  api-docs:
    path: /int/v1/docs/openapi
  swagger-ui:
    path: /int/v1/docs/swagger